---
- hosts: rke2_offline
  become: true
  vars:
    rke2_offline_folder_path: ~/rke2_playbook/ 
    rke2_home_folder_path: /etc/rancher/rke2/
    rke2_image_path: /var/lib/rancher/rke2/agent/images/
    rke2_tar_images_file_path: ~/rke2_playbook/rke2_offline_images.tar.gz
    rke2_binary_file_path: ~/rke2_playbook/rke2.linux-amd64
    rke2_registry_file_path: ~/rke2_playbook/config_files/registries.yaml 
    rke2_local_bin_path: /usr/local/bin/rke2
    rke2_cert_manager_folder_path: ~/rke2_playbook/cert-manager
    rke2_rancher_folder_path: ~/rke2_playbook/rancher
  tasks:  
  - name: Creating a rke2 offline folder
    file:
      path: "{{ rke2_offline_folder_path }}"
      state: directory    
  - name: Creating a rke2 home directory    
    file:
      path: "{{ rke2_home_folder_path }}"  
      state: directory
  - name: Creating a rke2 offline images home directory    
    file:
      path: "{{ rke2_image_path }}"  
      state: directory      
  - name: Copying rke2 files to the nodes
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{item.mode}}"
    with_items:
      - { src: "{{rke2_tar_images_file_path}}", dest: "{{rke2_tar_images_file_path}}", mode: '0644'}
      - { src: "{{rke2_binary_file_path}}", dest: "{{rke2_binary_file_path}}", mode: '0755'}
      - { src: "{{rke2_registry_file_path}}", dest: "{{rke2_home_folder_path}}", mode: '0644'}
      - { src: "{{rke2_cert_manager_folder_path}}", dest: "{{rke2_offline_folder_path}}", mode: '0664'}
      - { src: "{{rke2_rancher_folder_path}}", dest: "{{rke2_offline_folder_path}}", mode: '0664'}
  - name: Extracting the rke2 tar images file 
    unarchive:
      src: "{{ rke2_tar_images_file_path }}"
      dest: "{{ rke2_image_path }}"
      remote_src: yes
  - name: Moving the rke2 binary file to local/bin folder
    command: mv "{{rke2_binary_file_path}}" "{{rke2_local_bin_path}}"    