tls-san:
  - "cluster.local"
  - "192.168.1.30"
  - "node01"
data-dir: "/var/lib/rancher/rke2"
cluster-cidr: "10.42.0.0/16" 
service-cidr: "10.43.0.0/16" 
cluster-dns: "10.43.0.10" 
cluster-domain: "cluster.local" 
token: "rkesecret" 
write-kubeconfig: "/root/.kube/config" 
write-kubeconfig-mode: "0644"   
node-name: "node01" 
node-label: 
  - "nodename=node01" 
  - "clustername=cluster.local" 
node-ip: "192.168.1.30" 
advertise-address: "192.168.1.30"    